### ISSUE TITLE
[Bug]: Missing stack upgrades for Sophisticated Backpacks.

### ISSUE THREAD

**Issue by Shadow-1317** [dr3ams/Industrial-Village#37]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6c

### Describe your issue

Can't make or find the recipe for any of the Stack upgrades for Sophisticated Backpacks.

### Steps to reproduce the issue

1. Open inventory and search for recipe.
2. Try to manually make item.

### Additional Information

I tried to restart and see if that fixed it. I also tried to find it in the quest book under storage.

**Comment by Gunner76th** [comment]
This isn't a bug or issue with the modpack.  They were intentionally removed in 1.6 as stated in the change log due to a discovered issue in the modpack related to them.  

If the issue can be resolved they will be added back.  If it can't be the quest will likely be removed at a future date.  

I suggest joining our discord also to stay up to date on things work the modpack.
