### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by pepe515** [dr3ams/Industrial-Village#62]
### General Info

- [ ] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1

### Describe your issue

Hey, I can't launch the modpack, it keeps crashing and shows this.
need help.

 

### Additional Information

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe563f2b60, pid=32444, tid=32184
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x192b60]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://aka.ms/minecraftjavacrashes
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by Gunner76th** [comment]
You are using an outdated version of the modpack. We are currently on version 1.7b

Also please do not copy and paste log data to the issue ticket, Drag and Drop the crash report, hs err pid, latest, or other files directly into the github report. Copy and pasting it like you have makes it hard to read, not to mention you failed to post the entire log. 

Please properly attach the hs err pid file here so that we can read it.

**Comment by Gunner76th** [comment]
Also what specific CPU and GPU are you using?

**Comment by pepe515** [comment]
AMD Ryzen 5 5600G with Radeon Graphics    , 12 cores, 15G,  Windows 11 , 64 bit 

We were going to do it, but something happened and now it's just falling apart and throwing errors.
and use 1.7b

**Comment by pepe515** [comment]
[error.log](https://github.com/user-attachments/files/17510337/error.log)

Here I send the whole error.

**Comment by Gunner76th** [comment]
Your issue is because you do not have the proper drivers installed for your GPU/CPU

https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen/ryzen-5000-series/amd-ryzen-5-5600g.html

using the link above, download the drivers for your windows version. I also assume that your PC/laptop does not have a dedicated graphics card?

**Comment by pepe515** [comment]
Thank you, that's cool now, and yes, I don't have a video card, it's integrated in the processor
